### ISSUE TITLE
[enhancement] Add python formatter `yapf` to python scripts

### ISSUE THREAD

**Issue by BobAnkh** [BobAnkh/LinuxBeginner#26]
Plan to add python formatter `yapf`:

1. Check if all python scripts pass `yapf` daily
2. If some scripts not pass the check above, format them with `yapf` and update the scripts

**Comment by BobAnkh** [comment]
Would you try to do that? @Kelly510 

If you have made any progress, please post something here.

**Comment by Kelly510** [comment]
OK I'll try my best. @BobAnkh 
I've learned yapf, pygithub and part of github action. Today I've worked out the basic frame. The following step is to learn how to run a python script in github action.

**Comment by BobAnkh** [comment]
Ok. See this if you want to use python in a github action: [python-github action](https://docs.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions)

**Comment by Kelly510** [comment]
I plan to format existing python scripts manually and new-pushed scripts automatically. I've worked out a version but still have problem testing it.

**Comment by BobAnkh** [comment]
So please describe your problems in more details, otherwise I can't be more help.

**Comment by Kelly510** [comment]
I added yapf.yml in branch feat/yapf in my forked repo, and pushed a python scripts to folder scripts in branch master. But yapf  doesn't work as expected.

**Comment by BobAnkh** [comment]
So do you have `yapf.yml` in your **master** branch?

It seems that you can read docs more carefully :joy:

**Comment by Kelly510** [comment]
I just pushed `yapf.yml` to master branch and pushed a new test2.py. But it still doesn't work.

**Comment by BobAnkh** [comment]
I think there may be something wrong with your workflow file `yapf.yml`.

A better way to check is that you just test from a origin python workflow and add your feature one by one.

**Comment by Kelly510** [comment]
I'm using PyGithub to get access to repo and interact with it. Here are some steps I conceive:

- [x] get access to repo
```python
from github import Github
g = Github("access_token")
repo = g.get_repo("repo_name")
contents = repo.get_contents("path")
```

- [x] fetch all python scripts
```python
pyscripts = []
for content_file in contents:
    if content_file.path[-3:] == ".py":
        pyscripts.append(content_file)
print(pyscripts)
```

- [ ] format all python scripts
- [ ] substitute with formatted python scripts

In the third step I found out that format function `FormatFile` can be only used to local files but not remote file in repo. In this case I need to clone those .py to my computer's certain path and format them. But in an github action where shall I clone? Or is there a way we don't need to clone?

Also, as you can see above, access token to a repo must be included in the .yml file which can be seen by public. I think it may be unsafe.

**Comment by BobAnkh** [comment]
Well, in Github Action, it actually clone this repo to its runner(server) to conduct the workflow. Please read its docs more carefully. Also, check the official action `Checkout` for some relevant info. You can see in my `contributor.py`, where I modify its content and use update function to commit the changes. Also the pr for `md2pdf` finds a way to convert md file to pdfs, which creates new pdfs and commit them. Maybe this is also helpful to you?

As for the access token, we use `secrests` to deal with this problem. Also this can be found in Github Action's docs. You can see how my workflow and py script implement using secrets as an example.

Besides, I suggest you to use regex to match `.py` instead of string match.
