### ISSUE TITLE
[enhancement]add 'grep' to LinuxCommand

### ISSUE THREAD

**Issue by nagi2330** [BobAnkh/LinuxBeginner#41]
## Is your feature request related to a problem? Please describe

I found that a most commonly-used command 'grep' has not been included in the doc.

## Description of the new feature/enhancement

The whole explanation of 'grep' will be added, maybe along with a few samples of how to write regular expression. 
However, I am not sure how much content of regular expression should be conveyed. Perhaps I only need to explain about '*','.'and'[]'?
In addition, a contrast of 'grep' and 'find' will be added, following the style of the contrast between 'more' and 'less'.

**Comment by BobAnkh** [comment]
> However, I am not sure how much content of regular expression should be conveyed. Perhaps I only need to explain about '*','.'and'[]'?

You can just explain what kind of things will your regex match by some examples, e.g. `^feature` will match `feature` and `feature-request` but not `ffeature`.

**Comment by nagi2330** [comment]
got it! I will start the work these days.
