### ISSUE TITLE
[enhancement] Complete Linux tool Tree

### ISSUE THREAD

**Issue by BobAnkh** [BobAnkh/LinuxBeginner#8]
It is a good start for those who want to make their first contribution in this repo.

Writing the docs of this useful Linux tool `Tree` is easy.

**Comment by nagi2330** [comment]
I would like to take charge of this part. However, I find that we haven't came up with any merged introduction on Linux tools. I am not sure about the detailed format and content to follow yet. @BobAnkh

**Comment by BobAnkh** [comment]
Actually, there is a open pr related with tool `vim`. Maybe you can look up that pr as a ref. Also you can follow the opinion of command and adjust the content of `tree` as you want.

**Comment by nagi2330** [comment]
> Actually, there is a open pr related with tool `vim`. Maybe you can look up that pr as a ref. Also you can follow the opinion of command and adjust the content of `tree` as you want.

Got it！I will start ASAP these days
